apiVersion: v1
kind: ConfigMap
metadata:
  name: ws-benchmark
data:
  application.yml: |-
    server:
      servlet:
        context-path: /ws-benchmark

    spring:
      datasource:
        url: jdbc:mysql://host.docker.internal:3306/benchmark
        username: algorhythmic92
        password: ${BENCHMARK_DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        open-in-view: false
        hibernate:
          ddl-auto: update
        show-sql: true
