apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      volumes:
          - name: ws-benchmark
            configMap:
              name: ws-benchmark
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.container.port }}
          volumeMounts:
            - name: ws-benchmark
              mountPath: /config
          env:
          {{- range .Values.secrets }}
          - name: {{ .key }}
            valueFrom:
              secretKeyRef:
                name: {{ .name }}
                key: {{ .key }}
          {{- end }}
