server:
  servlet:
    context-path: /ws-benchmark

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/benchmark
    username: algorhythmic92
    password: ${BENCHMARK_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ${BENCHMARK_WEB_GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${BENCHMARK_WEB_GOOGLE_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid,profile
            redirectUri: http://localhost:8080/login/oauth2/code/google

